# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 842492aa50603510dfd7a4920fada9f456a5264be62ec7ab4b9df9077965446ecb8be1af09bfd5e135817e8aed1f6b2a76fac93e963671310ff01df262bdc2fe

test:
  secret_key_base: 07a041ab0cea592fc1f3da8e14f65e15286e417b65a83c15ca1a70b2b9c163fc73d6b7a208e5742c37ea64b609e650e571597d4bbcba1c468098c8f18aba535d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
